version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
  
  catalogapi:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CatalogDb=Host=catalogdb;Database=CatalogDb;Username=postgres;Password=postgres
    # ports:
    #   - "8080:8080"
    #   - "8081:8081"
    # depends_on:
    #   - catalogdb

volumes:
  postgres_catalog:


# version: '3.4'

# services:
#   catalogdb:
#     container_name: catalogdb
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=CatalogDb
#     restart: always
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_catalog:/var/lib/postgresql/data/

# volumes:
#   postgres_catalog:    